language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: gerardo+npm@gaderas.com
  api_key:
    secure: MgA+wX5GK0g6Wrac+fC7yBdKKge1FN342lkqtFcrUOX4iHwbaVvUysmvs55mntssiiWcmkUxxgLEfMtr8EqLnBOClMRumXp+z4vGm92gLIadcNxwt5Q3d5lbSoJr/cGgSwMbrX+0SxdeJLBYflaJjvW/hU1ggEe4a11VshFnBXQ=
  on:
    all_branches: true
    tags: true
    repo: sanx/metalsmith-date-in-filename
